version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestRenderingProject
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: Punith_KMAT_Salesforce_Sync
  gitServerName: test
  gitUrl: https://github.com/karthikbm
  gitUsername: PoojaAnandGit
  gitBranch: master
- name: CoupaTestPackage
  gitServerName: test
  gitUrl: https://github.com/karthikbm
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: TestWorkdayConnector
  gitServerName: test
  gitUrl: https://github.com/karthikbm
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: ShopifyTest1011
  gitServerName: test
  gitUrl: https://github.com/karthikbm
  gitUsername: PoojaAnandGit
  gitBranch: master
- name: WmShopifyProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: latest
